# 08 — Experimentos

Este notebook compara variantes ligeras del modelo VLA. Todos los experimentos usan exactamente las mismas particiones de **train** y **validation**; el conjunto de **test** queda reservado para el notebook 09.

## 1. Configuración e imports

Se reutilizan los embeddings cacheados de CLIP del notebook 04. CLIP no se vuelve a entrenar: solo se entrenan el Transformer de fusión y el decodificador.

In [1]:
from pathlib import Path
import json
import random
import sys

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader, TensorDataset

NOTEBOOK_DIR = Path.cwd().resolve()
ROOT_DIR = NOTEBOOK_DIR.parent if (NOTEBOOK_DIR.parent / 'src').exists() else NOTEBOOK_DIR
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

from src.evaluation import benchmark_inference, evaluate_actions, select_f1_threshold
from src.project_config import CACHE_DIR, PROJECT_DIR, experiment_dirs
from src.train import load_checkpoint, train_model
from src.vla_model import VLA

ROOT_DIR = PROJECT_DIR
SEED = 42
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
BATCH_SIZE = 16
LEARNING_RATE = 3e-4
WEIGHT_DECAY = 1e-4
EPOCHS_MAX = 50
PATIENCE = 7
# None usa todas las muestras. Puede cambiarse por un entero para una prueba rápida.
MAX_TRAIN_SAMPLES = None

def fijar_semilla(seed=SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

fijar_semilla()
RUTAS = experiment_dirs('experimentos_vla')
print(f'Dispositivo: {DEVICE} | semilla: {SEED}')
print(f'Resultados: {RUTAS["results"]}')

Dispositivo: cpu | semilla: 42
Resultados: C:\TFM_Codigo\TFM-VLA\results\experimentos_vla

## 2. Carga de datos y preparación de lotes

Se cargan únicamente `train` y `validation`. Las acciones tienen el orden `[terminate, x, y, z, rx, ry, rz, gripper]`.

In [2]:
EMBEDDING_DIM = 512
OUTPUT_DIM = 8

def cargar_particion(nombre):
    ruta = CACHE_DIR / f'{nombre}.npz'
    if not ruta.exists():
        raise FileNotFoundError(f'No existe {ruta}. Ejecuta antes 04_clip_embeddings.ipynb.')
    with np.load(ruta) as datos:
        requeridas = {'imagenes_static', 'imagenes_gripper', 'textos', 'acciones'}
        if not requeridas.issubset(datos.files):
            raise KeyError(f'{nombre}: se esperaban las claves {requeridas}')
        arrays = tuple(np.asarray(datos[clave], dtype=np.float32) for clave in
                       ('imagenes_static', 'imagenes_gripper', 'textos', 'acciones'))
    static, gripper, texto, acciones = arrays
    if not (len(static) == len(gripper) == len(texto) == len(acciones)):
        raise ValueError(f'{nombre}: longitudes inconsistentes')
    if static.shape[1:] != (EMBEDDING_DIM,) or gripper.shape[1:] != (EMBEDDING_DIM,) or texto.shape[1:] != (EMBEDDING_DIM,):
        raise ValueError(f'{nombre}: embeddings con dimensión inesperada')
    if acciones.shape[1:] != (OUTPUT_DIM,) or not all(np.isfinite(x).all() for x in arrays):
        raise ValueError(f'{nombre}: acciones o embeddings no válidos')
    return arrays

particiones = {nombre: cargar_particion(nombre) for nombre in ('train', 'validation')}
if MAX_TRAIN_SAMPLES is not None:
    particiones['train'] = tuple(array[:MAX_TRAIN_SAMPLES] for array in particiones['train'])

for nombre, (static, gripper, texto, acciones) in particiones.items():
    print(f'{nombre:10s}: static={static.shape}, gripper={gripper.shape}, texto={texto.shape}, acciones={acciones.shape}')

with (ROOT_DIR / 'data' / 'parametros_normalizacion.json').open(encoding='utf-8') as archivo:
    normalizacion = json.load(archivo)
MINIMO = np.asarray(normalizacion['minimo'], dtype=np.float32)
ESCALA = np.asarray(normalizacion['escala'], dtype=np.float32)

train     : static=(190212, 512), gripper=(190212, 512), texto=(190212, 512), acciones=(190212, 8)
validation: static=(23760, 512), gripper=(23760, 512), texto=(23760, 512), acciones=(23760, 8)

## 3. Funciones reutilizables

La misma función entrena, recupera el mejor checkpoint y calcula las métricas de validación de cada variante. Esto evita repetir código y garantiza que el procedimiento sea igual en todos los casos.

In [3]:
def aplicar_modalidades(arrays, modalidad):
    """Anula modalidades para conservar la misma arquitectura de tres tokens."""
    static, gripper, texto, acciones = arrays
    if modalidad == 'imagen':
        texto = np.zeros_like(texto)
    elif modalidad == 'texto':
        static = np.zeros_like(static)
        gripper = np.zeros_like(gripper)
    elif modalidad != 'imagen_texto':
        raise ValueError(f'Modalidad no reconocida: {modalidad}')
    return static, gripper, texto, acciones

def crear_loaders(train_arrays, validation_arrays):
    train_dataset = TensorDataset(*(torch.from_numpy(array) for array in train_arrays))
    validation_dataset = TensorDataset(*(torch.from_numpy(array) for array in validation_arrays))
    # Se reinicia el generador para que el orden de train sea comparable.
    generator = torch.Generator().manual_seed(SEED)
    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, generator=generator, num_workers=0)
    validation_loader = DataLoader(validation_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
    return train_loader, validation_loader

def crear_modelo(config):
    return VLA(
        clip_encoder=None, embedding_dim=EMBEDDING_DIM, fusion_dim=config['fusion_dim'],
        decoder_hidden_dim=128, num_layers=config['num_layers'], num_heads=4,
        feedforward_dim=config['fusion_dim'] * 2, dropout=0.1,
    ).to(DEVICE)

def predecir(modelo, loader):
    predicciones, objetivos = [], []
    modelo.eval()
    with torch.no_grad():
        for static, gripper, texto, accion in loader:
            salida = modelo(static_embeddings=static.to(DEVICE), gripper_embeddings=gripper.to(DEVICE), text_embeddings=texto.to(DEVICE))
            predicciones.append(salida.cpu())
            objetivos.append(accion)
    return torch.cat(predicciones).numpy(), torch.cat(objetivos).numpy()

def ejecutar_experimento(config):
    fijar_semilla()
    nombre = config['name']
    rutas = experiment_dirs(f'experimentos_vla/{nombre}')
    train_arrays = aplicar_modalidades(particiones['train'], config['modalidad'])
    validation_arrays = aplicar_modalidades(particiones['validation'], config['modalidad'])
    train_loader, validation_loader = crear_loaders(train_arrays, validation_arrays)
    positivos_terminate = int((train_arrays[3][:, 0] >= 0.5).sum())
    negativos_terminate = len(train_arrays[3]) - positivos_terminate
    terminate_positive_weight = negativos_terminate / max(positivos_terminate, 1)
    modelo = crear_modelo(config)
    optimizador = torch.optim.AdamW(modelo.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    checkpoint_path = rutas['checkpoints'] / 'best.pt'
    configuracion = {**config, 'seed': SEED, 'batch_size': BATCH_SIZE, 'learning_rate': LEARNING_RATE,
                     'weight_decay': WEIGHT_DECAY, 'epochs_max': EPOCHS_MAX, 'patience': PATIENCE,
                     'terminate_positive_weight': terminate_positive_weight}
    resumen = train_model(modelo, train_loader, validation_loader, optimizador, DEVICE,
                           epochs=EPOCHS_MAX, patience=PATIENCE, checkpoint_path=checkpoint_path, config=configuracion,
                           terminate_positive_weight=terminate_positive_weight)
    recuperado = crear_modelo(config)
    checkpoint = load_checkpoint(checkpoint_path, recuperado, map_location=DEVICE)
    y_pred, y_true = predecir(recuperado, validation_loader)
    terminate_threshold = select_f1_threshold(y_pred[:, 0], y_true[:, 0])
    metricas = evaluate_actions(y_pred, y_true, MINIMO, ESCALA, terminate_threshold=terminate_threshold)
    total = sum(p.numel() for p in recuperado.parameters())
    entrenables = sum(p.numel() for p in recuperado.parameters() if p.requires_grad)
    n_tiempo = min(32, len(validation_arrays[0]))
    entrada_tiempo = [torch.from_numpy(array[:n_tiempo]).to(DEVICE) for array in validation_arrays[:3]]
    inferencia = benchmark_inference(lambda: recuperado(static_embeddings=entrada_tiempo[0], gripper_embeddings=entrada_tiempo[1], text_embeddings=entrada_tiempo[2]), n_tiempo)
    resultado = {**configuracion, 'best_epoch': resumen['best_epoch'],
                 'best_validation_loss': resumen['best_validation_loss'],
                 'epochs_executed': resumen['epochs_executed'],
                 'total_training_time_seconds': resumen['total_training_time_seconds'],
                 'parameters_total': total, 'parameters_trainable': entrenables, 'terminate_threshold': terminate_threshold,
                 'validation_metrics': metricas, 'cached_inference': inferencia,
                 'checkpoint': str(checkpoint_path), 'history': resumen['history'], 'test_used': False}
    with (rutas['results'] / 'resultado.json').open('w', encoding='utf-8') as archivo:
        json.dump(resultado, archivo, indent=2, ensure_ascii=False)
    print(f'{nombre}: validation loss={resultado["best_validation_loss"]:.6f} | terminate F1={metricas["terminate"]["f1"]:.4f} | época={resultado["best_epoch"]}')
    return resultado

## 4. Configuraciones a comparar

Se entrena una referencia VLA estándar y cinco variantes. La referencia (2 capas y dimensión 256) se reutiliza en la comparación de capas, dimensión y modalidades, por lo que no se entrena dos veces.

In [4]:
EXPERIMENTOS = [
    {'name': 'vla_referencia', 'grupo': 'referencia', 'descripcion': 'VLA estándar', 'num_layers': 2, 'fusion_dim': 256, 'modalidad': 'imagen_texto'},
    {'name': 'capas_1', 'grupo': 'capas', 'descripcion': '1 capa', 'num_layers': 1, 'fusion_dim': 256, 'modalidad': 'imagen_texto'},
    {'name': 'capas_3', 'grupo': 'capas', 'descripcion': '3 capas', 'num_layers': 3, 'fusion_dim': 256, 'modalidad': 'imagen_texto'},
    {'name': 'dimension_128', 'grupo': 'dimension', 'descripcion': 'd_model = 128', 'num_layers': 2, 'fusion_dim': 128, 'modalidad': 'imagen_texto'},
    {'name': 'solo_imagen', 'grupo': 'modalidades', 'descripcion': 'Solo imagen', 'num_layers': 2, 'fusion_dim': 256, 'modalidad': 'imagen'},
    {'name': 'solo_texto', 'grupo': 'modalidades', 'descripcion': 'Solo texto', 'num_layers': 2, 'fusion_dim': 256, 'modalidad': 'texto'},
]
pd.DataFrame(EXPERIMENTOS)[['name', 'grupo', 'descripcion', 'num_layers', 'fusion_dim', 'modalidad']]

,name,grupo,descripcion,num_layers,fusion_dim,modalidad
0,vla_referencia,referencia,VLA estándar,2,256,imagen_texto
1,capas_1,capas,1 capa,1,256,imagen_texto
2,capas_3,capas,3 capas,3,256,imagen_texto
3,dimension_128,dimension,d_model = 128,2,128,imagen_texto
4,solo_imagen,modalidades,Solo imagen,2,256,imagen
5,solo_texto,modalidades,Solo texto,2,256,texto

## 5. Ejecución de los experimentos

Cada configuración empieza con pesos iniciales y orden de entrenamiento reproducibles. En CPU, el conjunto completo puede requerir bastante tiempo; `MAX_TRAIN_SAMPLES` permite una ejecución de comprobación más corta sin modificar el flujo.

In [5]:
resultados = [ejecutar_experimento(config) for config in EXPERIMENTOS]

Entrenamiento 1/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/50 | train_loss=1.875079 | validation_loss=1.773455 | 514.8s

Entrenamiento 2/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/50 | train_loss=1.796163 | validation_loss=1.769495 | 414.0s

Entrenamiento 3/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/50 | train_loss=1.790255 | validation_loss=1.753205 | 406.4s

Entrenamiento 4/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/50 | train_loss=1.753585 | validation_loss=1.724269 | 408.0s

Entrenamiento 5/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/50 | train_loss=1.735785 | validation_loss=1.792266 | 413.7s

Entrenamiento 6/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/50 | train_loss=1.762251 | validation_loss=1.690819 | 407.3s

Entrenamiento 7/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/50 | train_loss=1.742914 | validation_loss=1.709866 | 412.1s

Entrenamiento 8/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/50 | train_loss=1.744309 | validation_loss=1.715830 | 427.2s

Entrenamiento 9/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/50 | train_loss=1.707579 | validation_loss=1.657205 | 436.4s

Entrenamiento 10/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/50 | train_loss=1.647639 | validation_loss=1.552547 | 443.9s

Entrenamiento 11/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 11/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 11/50 | train_loss=1.624925 | validation_loss=1.466913 | 407.5s

Entrenamiento 12/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 12/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 12/50 | train_loss=1.544014 | validation_loss=1.550297 | 411.1s

Entrenamiento 13/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 13/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 13/50 | train_loss=1.493261 | validation_loss=1.522982 | 403.9s

Entrenamiento 14/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 14/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 14/50 | train_loss=1.463934 | validation_loss=1.439791 | 406.5s

Entrenamiento 15/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 15/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 15/50 | train_loss=1.457617 | validation_loss=1.386543 | 413.0s

Entrenamiento 16/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 16/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 16/50 | train_loss=1.417889 | validation_loss=1.373546 | 403.8s

Entrenamiento 17/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 17/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 17/50 | train_loss=1.396323 | validation_loss=1.414102 | 399.7s

Entrenamiento 18/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 18/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 18/50 | train_loss=1.382635 | validation_loss=1.377602 | 424.1s

Entrenamiento 19/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 19/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 19/50 | train_loss=1.378190 | validation_loss=1.371345 | 406.1s

Entrenamiento 20/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 20/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 20/50 | train_loss=1.388487 | validation_loss=1.428341 | 401.2s

Entrenamiento 21/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 21/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 21/50 | train_loss=1.372562 | validation_loss=1.336362 | 407.0s

Entrenamiento 22/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 22/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 22/50 | train_loss=1.353505 | validation_loss=1.331974 | 401.1s

Entrenamiento 23/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 23/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 23/50 | train_loss=1.345943 | validation_loss=1.310899 | 401.0s

Entrenamiento 24/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 24/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 24/50 | train_loss=1.325659 | validation_loss=1.305680 | 409.6s

Entrenamiento 25/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 25/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 25/50 | train_loss=1.310713 | validation_loss=1.311216 | 407.5s

Entrenamiento 26/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 26/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 26/50 | train_loss=1.299023 | validation_loss=1.280082 | 405.6s

Entrenamiento 27/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 27/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 27/50 | train_loss=1.302607 | validation_loss=1.267090 | 410.8s

Entrenamiento 28/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 28/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 28/50 | train_loss=1.299057 | validation_loss=1.293776 | 408.7s

Entrenamiento 29/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 29/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 29/50 | train_loss=1.316183 | validation_loss=1.310247 | 397.8s

Entrenamiento 30/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 30/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 30/50 | train_loss=1.293009 | validation_loss=1.292346 | 404.7s

Entrenamiento 31/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 31/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 31/50 | train_loss=1.265866 | validation_loss=1.269157 | 407.6s

Entrenamiento 32/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 32/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 32/50 | train_loss=1.273662 | validation_loss=1.306812 | 393.2s

Entrenamiento 33/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 33/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 33/50 | train_loss=1.261817 | validation_loss=1.396971 | 398.4s

Entrenamiento 34/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 34/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 34/50 | train_loss=1.257914 | validation_loss=1.348181 | 404.1s
Early stopping: 7 épocas sin mejora.
vla_referencia: validation loss=1.267090 | terminate F1=0.1980 | época=27

Entrenamiento 1/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/50 | train_loss=1.730563 | validation_loss=1.595824 | 234.2s

Entrenamiento 2/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/50 | train_loss=1.530456 | validation_loss=1.400261 | 235.7s

Entrenamiento 3/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/50 | train_loss=1.438769 | validation_loss=1.353909 | 235.6s

Entrenamiento 4/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/50 | train_loss=1.398980 | validation_loss=1.479000 | 241.0s

Entrenamiento 5/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/50 | train_loss=1.354720 | validation_loss=1.269458 | 246.8s

Entrenamiento 6/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/50 | train_loss=1.335132 | validation_loss=1.283692 | 235.0s

Entrenamiento 7/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/50 | train_loss=1.314510 | validation_loss=1.297625 | 237.1s

Entrenamiento 8/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/50 | train_loss=1.287096 | validation_loss=1.240731 | 235.4s

Entrenamiento 9/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/50 | train_loss=1.262145 | validation_loss=1.231589 | 238.1s

Entrenamiento 10/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/50 | train_loss=1.243525 | validation_loss=1.302412 | 238.4s

Entrenamiento 11/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 11/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 11/50 | train_loss=1.226409 | validation_loss=1.230481 | 236.2s

Entrenamiento 12/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 12/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 12/50 | train_loss=1.222189 | validation_loss=1.561738 | 233.4s

Entrenamiento 13/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 13/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 13/50 | train_loss=1.212831 | validation_loss=1.335811 | 239.6s

Entrenamiento 14/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 14/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 14/50 | train_loss=1.187308 | validation_loss=1.262010 | 233.3s

Entrenamiento 15/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 15/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 15/50 | train_loss=1.179530 | validation_loss=1.208420 | 241.4s

Entrenamiento 16/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 16/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 16/50 | train_loss=1.169796 | validation_loss=1.215012 | 236.5s

Entrenamiento 17/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 17/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 17/50 | train_loss=1.151041 | validation_loss=1.176099 | 245.2s

Entrenamiento 18/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 18/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 18/50 | train_loss=1.147468 | validation_loss=1.241709 | 247.4s

Entrenamiento 19/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 19/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 19/50 | train_loss=1.140744 | validation_loss=1.284978 | 234.1s

Entrenamiento 20/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 20/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 20/50 | train_loss=1.158789 | validation_loss=1.189384 | 241.3s

Entrenamiento 21/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 21/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 21/50 | train_loss=1.128665 | validation_loss=1.258851 | 233.3s

Entrenamiento 22/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 22/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 22/50 | train_loss=1.106056 | validation_loss=1.170216 | 236.2s

Entrenamiento 23/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 23/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 23/50 | train_loss=1.109076 | validation_loss=1.265724 | 241.1s

Entrenamiento 24/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 24/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 24/50 | train_loss=1.112095 | validation_loss=1.178193 | 245.3s

Entrenamiento 25/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 25/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 25/50 | train_loss=1.117190 | validation_loss=1.186945 | 241.2s

Entrenamiento 26/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 26/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 26/50 | train_loss=1.099335 | validation_loss=1.167497 | 284.9s

Entrenamiento 27/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 27/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 27/50 | train_loss=1.098853 | validation_loss=1.238109 | 343.5s

Entrenamiento 28/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 28/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 28/50 | train_loss=1.090573 | validation_loss=1.156638 | 249.6s

Entrenamiento 29/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 29/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 29/50 | train_loss=1.081368 | validation_loss=1.180330 | 239.0s

Entrenamiento 30/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 30/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 30/50 | train_loss=1.077413 | validation_loss=1.458865 | 240.4s

Entrenamiento 31/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 31/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 31/50 | train_loss=1.073243 | validation_loss=1.281453 | 236.4s

Entrenamiento 32/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 32/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 32/50 | train_loss=1.064992 | validation_loss=1.181098 | 256.5s

Entrenamiento 33/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 33/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 33/50 | train_loss=1.073905 | validation_loss=1.206973 | 245.6s

Entrenamiento 34/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 34/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 34/50 | train_loss=1.057417 | validation_loss=1.242685 | 247.8s

Entrenamiento 35/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 35/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 35/50 | train_loss=1.055217 | validation_loss=1.218864 | 249.3s
Early stopping: 7 épocas sin mejora.
capas_1: validation loss=1.156638 | terminate F1=0.2385 | época=28

Entrenamiento 1/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/50 | train_loss=1.927704 | validation_loss=1.905416 | 540.0s

Entrenamiento 2/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/50 | train_loss=1.857913 | validation_loss=1.812479 | 520.8s

Entrenamiento 3/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/50 | train_loss=1.775192 | validation_loss=1.778118 | 541.9s

Entrenamiento 4/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/50 | train_loss=1.773871 | validation_loss=1.768056 | 534.7s

Entrenamiento 5/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/50 | train_loss=1.753413 | validation_loss=1.706138 | 536.3s

Entrenamiento 6/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/50 | train_loss=1.750502 | validation_loss=1.679254 | 562.5s

Entrenamiento 7/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/50 | train_loss=1.786914 | validation_loss=1.720305 | 563.7s

Entrenamiento 8/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/50 | train_loss=1.742357 | validation_loss=1.689561 | 544.4s

Entrenamiento 9/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/50 | train_loss=1.713971 | validation_loss=1.678992 | 574.3s

Entrenamiento 10/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/50 | train_loss=1.665354 | validation_loss=1.615074 | 542.9s

Entrenamiento 11/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 11/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 11/50 | train_loss=1.646483 | validation_loss=1.810686 | 556.5s

Entrenamiento 12/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 12/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 12/50 | train_loss=1.613866 | validation_loss=1.525434 | 569.3s

Entrenamiento 13/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 13/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 13/50 | train_loss=1.579969 | validation_loss=1.864840 | 576.4s

Entrenamiento 14/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 14/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 14/50 | train_loss=1.567473 | validation_loss=1.495540 | 552.7s

Entrenamiento 15/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 15/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 15/50 | train_loss=1.599808 | validation_loss=1.560298 | 571.7s

Entrenamiento 16/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 16/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 16/50 | train_loss=1.574503 | validation_loss=1.592418 | 555.4s

Entrenamiento 17/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 17/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 17/50 | train_loss=1.536964 | validation_loss=1.477022 | 577.8s

Entrenamiento 18/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 18/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 18/50 | train_loss=1.529730 | validation_loss=1.466847 | 579.7s

Entrenamiento 19/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 19/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 19/50 | train_loss=1.527582 | validation_loss=1.490321 | 610.7s

Entrenamiento 20/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 20/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 20/50 | train_loss=1.512237 | validation_loss=1.488697 | 567.8s

Entrenamiento 21/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 21/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 21/50 | train_loss=1.493606 | validation_loss=1.444460 | 595.1s

Entrenamiento 22/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 22/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 22/50 | train_loss=1.501209 | validation_loss=1.528597 | 570.0s

Entrenamiento 23/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 23/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 23/50 | train_loss=1.554934 | validation_loss=1.488589 | 578.5s

Entrenamiento 24/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 24/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 24/50 | train_loss=1.502979 | validation_loss=1.439401 | 605.0s

Entrenamiento 25/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 25/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 25/50 | train_loss=1.497581 | validation_loss=1.516354 | 594.3s

Entrenamiento 26/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 26/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 26/50 | train_loss=1.497261 | validation_loss=1.575022 | 565.4s

Entrenamiento 27/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 27/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 27/50 | train_loss=1.482370 | validation_loss=1.449729 | 579.1s

Entrenamiento 28/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 28/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 28/50 | train_loss=1.479536 | validation_loss=1.455062 | 560.7s

Entrenamiento 29/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 29/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 29/50 | train_loss=1.483117 | validation_loss=1.559473 | 593.0s

Entrenamiento 30/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 30/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 30/50 | train_loss=1.496852 | validation_loss=1.474634 | 578.4s

Entrenamiento 31/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 31/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 31/50 | train_loss=1.472430 | validation_loss=1.521484 | 565.5s
Early stopping: 7 épocas sin mejora.
capas_3: validation loss=1.439401 | terminate F1=0.1414 | época=24

Entrenamiento 1/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/50 | train_loss=1.715595 | validation_loss=1.542264 | 238.6s

Entrenamiento 2/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/50 | train_loss=1.513204 | validation_loss=1.498357 | 230.8s

Entrenamiento 3/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/50 | train_loss=1.451049 | validation_loss=1.361780 | 229.7s

Entrenamiento 4/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/50 | train_loss=1.410564 | validation_loss=1.392449 | 237.3s

Entrenamiento 5/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/50 | train_loss=1.381139 | validation_loss=1.282877 | 234.7s

Entrenamiento 6/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/50 | train_loss=1.352264 | validation_loss=1.305133 | 240.5s

Entrenamiento 7/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/50 | train_loss=1.324627 | validation_loss=1.268039 | 234.7s

Entrenamiento 8/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/50 | train_loss=1.306088 | validation_loss=1.252646 | 236.7s

Entrenamiento 9/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/50 | train_loss=1.288444 | validation_loss=1.283729 | 240.1s

Entrenamiento 10/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/50 | train_loss=1.278357 | validation_loss=1.417847 | 235.6s

Entrenamiento 11/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 11/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 11/50 | train_loss=1.263446 | validation_loss=1.237618 | 238.6s

Entrenamiento 12/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 12/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 12/50 | train_loss=1.264340 | validation_loss=1.315882 | 238.7s

Entrenamiento 13/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 13/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 13/50 | train_loss=1.241610 | validation_loss=1.260506 | 234.6s

Entrenamiento 14/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 14/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 14/50 | train_loss=1.263785 | validation_loss=1.448405 | 250.2s

Entrenamiento 15/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 15/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 15/50 | train_loss=1.235241 | validation_loss=1.198086 | 243.2s

Entrenamiento 16/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 16/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 16/50 | train_loss=1.210983 | validation_loss=1.258725 | 241.5s

Entrenamiento 17/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 17/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 17/50 | train_loss=1.191103 | validation_loss=1.230612 | 236.2s

Entrenamiento 18/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 18/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 18/50 | train_loss=1.187780 | validation_loss=1.235755 | 237.7s

Entrenamiento 19/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 19/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 19/50 | train_loss=1.173406 | validation_loss=1.328311 | 236.0s

Entrenamiento 20/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 20/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 20/50 | train_loss=1.170328 | validation_loss=1.266943 | 235.3s

Entrenamiento 21/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 21/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 21/50 | train_loss=1.160193 | validation_loss=1.201695 | 237.0s

Entrenamiento 22/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 22/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 22/50 | train_loss=1.152204 | validation_loss=1.206437 | 231.9s
Early stopping: 7 épocas sin mejora.
dimension_128: validation loss=1.198086 | terminate F1=0.1918 | época=15

Entrenamiento 1/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/50 | train_loss=1.984070 | validation_loss=2.049889 | 395.4s

Entrenamiento 2/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/50 | train_loss=2.020540 | validation_loss=1.813706 | 386.8s

Entrenamiento 3/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/50 | train_loss=1.784084 | validation_loss=1.739115 | 396.9s

Entrenamiento 4/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/50 | train_loss=1.790881 | validation_loss=1.781470 | 419.6s

Entrenamiento 5/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/50 | train_loss=1.777320 | validation_loss=1.738333 | 396.3s

Entrenamiento 6/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/50 | train_loss=1.763852 | validation_loss=1.737878 | 407.7s

Entrenamiento 7/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/50 | train_loss=1.750383 | validation_loss=1.725905 | 397.4s

Entrenamiento 8/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/50 | train_loss=1.736204 | validation_loss=1.713394 | 394.4s

Entrenamiento 9/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/50 | train_loss=1.768374 | validation_loss=1.801607 | 401.9s

Entrenamiento 10/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/50 | train_loss=1.744821 | validation_loss=1.695366 | 408.7s

Entrenamiento 11/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 11/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 11/50 | train_loss=1.701006 | validation_loss=1.675306 | 404.1s

Entrenamiento 12/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 12/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 12/50 | train_loss=1.707229 | validation_loss=1.645619 | 404.1s

Entrenamiento 13/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 13/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 13/50 | train_loss=1.642429 | validation_loss=1.614678 | 445.7s

Entrenamiento 14/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 14/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 14/50 | train_loss=1.586505 | validation_loss=1.496518 | 424.7s

Entrenamiento 15/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 15/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 15/50 | train_loss=1.506557 | validation_loss=1.454001 | 414.0s

Entrenamiento 16/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 16/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 16/50 | train_loss=1.458623 | validation_loss=1.526798 | 400.9s

Entrenamiento 17/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 17/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 17/50 | train_loss=1.430346 | validation_loss=1.432494 | 428.5s

Entrenamiento 18/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 18/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 18/50 | train_loss=1.410789 | validation_loss=1.356009 | 419.0s

Entrenamiento 19/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 19/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 19/50 | train_loss=1.400608 | validation_loss=1.369451 | 412.0s

Entrenamiento 20/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 20/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 20/50 | train_loss=1.385286 | validation_loss=1.335909 | 413.8s

Entrenamiento 21/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 21/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 21/50 | train_loss=1.377883 | validation_loss=1.353093 | 408.3s

Entrenamiento 22/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 22/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 22/50 | train_loss=1.370156 | validation_loss=1.349670 | 417.4s

Entrenamiento 23/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 23/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 23/50 | train_loss=1.352099 | validation_loss=1.409257 | 421.6s

Entrenamiento 24/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 24/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 24/50 | train_loss=1.352205 | validation_loss=1.357391 | 408.2s

Entrenamiento 25/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 25/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 25/50 | train_loss=1.363337 | validation_loss=1.331536 | 408.8s

Entrenamiento 26/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 26/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 26/50 | train_loss=1.345051 | validation_loss=1.335214 | 409.6s

Entrenamiento 27/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 27/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 27/50 | train_loss=1.330169 | validation_loss=1.324961 | 410.6s

Entrenamiento 28/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 28/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 28/50 | train_loss=1.318276 | validation_loss=1.324257 | 413.1s

Entrenamiento 29/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 29/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 29/50 | train_loss=1.320908 | validation_loss=1.315181 | 404.7s

Entrenamiento 30/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 30/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 30/50 | train_loss=1.314531 | validation_loss=1.311800 | 401.9s

Entrenamiento 31/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 31/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 31/50 | train_loss=1.309208 | validation_loss=1.333169 | 425.5s

Entrenamiento 32/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 32/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 32/50 | train_loss=1.298950 | validation_loss=1.366704 | 415.9s

Entrenamiento 33/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 33/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 33/50 | train_loss=1.293974 | validation_loss=1.333047 | 414.2s

Entrenamiento 34/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 34/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 34/50 | train_loss=1.281474 | validation_loss=1.409253 | 424.3s

Entrenamiento 35/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 35/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 35/50 | train_loss=1.284000 | validation_loss=1.277784 | 433.6s

Entrenamiento 36/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 36/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 36/50 | train_loss=1.272586 | validation_loss=1.290628 | 433.2s

Entrenamiento 37/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 37/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 37/50 | train_loss=1.272526 | validation_loss=1.296174 | 428.6s

Entrenamiento 38/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 38/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 38/50 | train_loss=1.298083 | validation_loss=1.454231 | 454.7s

Entrenamiento 39/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 39/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 39/50 | train_loss=1.296601 | validation_loss=1.280628 | 471.6s

Entrenamiento 40/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 40/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 40/50 | train_loss=1.269270 | validation_loss=1.273273 | 456.6s

Entrenamiento 41/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 41/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 41/50 | train_loss=1.253433 | validation_loss=1.350247 | 422.4s

Entrenamiento 42/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 42/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 42/50 | train_loss=1.245877 | validation_loss=1.279949 | 438.7s

Entrenamiento 43/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 43/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 43/50 | train_loss=1.242945 | validation_loss=1.283523 | 432.7s

Entrenamiento 44/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 44/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 44/50 | train_loss=1.259977 | validation_loss=1.365675 | 448.8s

Entrenamiento 45/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 45/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 45/50 | train_loss=1.238271 | validation_loss=1.655515 | 441.3s

Entrenamiento 46/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 46/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 46/50 | train_loss=1.235050 | validation_loss=1.268711 | 433.0s

Entrenamiento 47/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 47/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 47/50 | train_loss=1.227620 | validation_loss=1.264883 | 437.3s

Entrenamiento 48/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 48/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 48/50 | train_loss=1.221950 | validation_loss=1.297156 | 416.5s

Entrenamiento 49/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 49/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 49/50 | train_loss=1.225913 | validation_loss=1.240672 | 417.7s

Entrenamiento 50/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 50/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 50/50 | train_loss=1.218787 | validation_loss=1.275042 | 413.2s
solo_imagen: validation loss=1.240672 | terminate F1=0.1852 | época=49

Entrenamiento 1/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/50 | train_loss=2.059711 | validation_loss=2.049829 | 400.0s

Entrenamiento 2/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/50 | train_loss=2.053107 | validation_loss=2.049891 | 385.6s

Entrenamiento 3/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/50 | train_loss=2.054181 | validation_loss=2.049803 | 391.2s

Entrenamiento 4/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/50 | train_loss=2.052518 | validation_loss=2.049840 | 388.9s

Entrenamiento 5/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/50 | train_loss=2.052005 | validation_loss=2.049972 | 424.8s

Entrenamiento 6/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/50 | train_loss=2.052356 | validation_loss=2.050016 | 385.6s

Entrenamiento 7/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/50 | train_loss=2.055996 | validation_loss=2.050539 | 386.3s

Entrenamiento 8/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/50 | train_loss=2.055934 | validation_loss=2.051651 | 393.8s

Entrenamiento 9/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/50 | train_loss=2.052249 | validation_loss=2.050423 | 394.3s

Entrenamiento 10/50:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/50:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/50 | train_loss=2.053834 | validation_loss=2.051351 | 391.6s
Early stopping: 7 épocas sin mejora.
solo_texto: validation loss=2.049803 | terminate F1=0.0299 | época=3

## 6. Comparación con el baseline MLP

El baseline se entrena en el notebook 05. Si su archivo de resultados de validación está disponible, se añade como referencia; si no, el notebook sigue siendo ejecutable y muestra una advertencia.

In [6]:
def cargar_baseline():
    ruta = ROOT_DIR / 'results' / 'baseline_mlp_binary_phase1' / 'baseline_mlp_binary_validation.json'
    if not ruta.exists():
        print('Baseline no disponible: ejecuta 05_baseline_mlp.ipynb para añadirlo a la comparación.')
        return None
    with ruta.open(encoding='utf-8') as archivo:
        baseline = json.load(archivo)
    return {
        'name': 'baseline_mlp', 'grupo': 'baseline', 'descripcion': 'MLP del notebook 05',
        'best_validation_loss': baseline['best_validation_loss'],
        'parameters_trainable': baseline['computational_efficiency']['trainable_parameters'],
        'validation_metrics': baseline['validation_action_metrics'],
    }

baseline = cargar_baseline()
if baseline is not None:
    resultados.append(baseline)

## 7. Resumen y guardado

La tabla resume las métricas principales de validación. El tiempo de inferencia corresponde solo al VLA sobre embeddings cacheados, porque CLIP está congelado e idéntico en todas las variantes; la medición completa del sistema se realizará en el notebook 09.

In [7]:
def fila_resumen(resultado):
    metricas = resultado['validation_metrics']
    fila = {
        'experimento': resultado['name'], 'grupo': resultado['grupo'], 'descripcion': resultado['descripcion'],
        'validation_loss': resultado['best_validation_loss'],
        'mae': metricas['continuous_normalized']['mae'],
        'rmse': metricas['continuous_normalized']['rmse'],
        'coseno_xyz': metricas['xyz_denormalized_cosine_similarity'],
        'terminate_f1': metricas['terminate']['f1'],
        'terminate_precision': metricas['terminate']['precision'],
        'terminate_recall': metricas['terminate']['recall'],
        'terminate_predicted_positives': metricas['terminate']['predicted_positives'],
        'terminate_threshold': metricas['terminate']['threshold'],
        'terminate_accuracy': metricas['terminate']['accuracy'],
        'parametros_entrenables': resultado['parameters_trainable'],
    }
    if 'cached_inference' in resultado:
        fila['inferencia_ms_muestra'] = resultado['cached_inference']['mean_ms_per_sample']
        fila['tiempo_entrenamiento_s'] = resultado['total_training_time_seconds']
    return fila

tabla_resultados = pd.DataFrame([fila_resumen(resultado) for resultado in resultados])
tabla_resultados = tabla_resultados.sort_values(['grupo', 'experimento']).reset_index(drop=True)
tabla_path = RUTAS['results'] / 'resumen_experimentos.csv'
json_path = RUTAS['results'] / 'resumen_experimentos.json'
tabla_resultados.to_csv(tabla_path, index=False)
with json_path.open('w', encoding='utf-8') as archivo:
    json.dump(resultados, archivo, indent=2, ensure_ascii=False)

display(tabla_resultados.round(4))
print(f'Resumen guardado en {tabla_path}')
print('El conjunto de test no se ha usado. El notebook 09 evaluará el modelo seleccionado.')

,experimento,grupo,descripcion,validation_loss,mae,rmse,coseno_xyz,terminate_f1,terminate_precision,terminate_recall,terminate_predicted_positives,terminate_threshold,terminate_accuracy,parametros_entrenables,inferencia_ms_muestra,tiempo_entrenamiento_s
0,baseline_mlp,baseline,MLP del notebook 05,1.0709,0.0349,0.0505,0.3125,0.2132,0.1829,0.2556,503,0.91,0.9714,920328,NaN,NaN
1,capas_1,capas,1 capa,1.1566,0.0365,0.0530,0.1298,0.2385,0.2074,0.2806,487,0.93,0.9729,824968,0.1061,8557.3923
2,capas_3,capas,3 capas,1.4394,0.0363,0.0536,0.0667,0.1414,0.0931,0.2944,1139,0.81,0.9458,1879176,0.2506,17566.8775
3,dimension_128,dimension,d_model = 128,1.1981,0.0364,0.0537,0.0737,0.1918,0.1480,0.2722,662,0.89,0.9652,414472,0.0707,5220.3314
4,solo_imagen,modalidades,Solo imagen,1.2407,0.0364,0.0534,0.0994,0.1852,0.1164,0.4528,1400,0.83,0.9396,1352072,0.1641,20939.8525
5,solo_texto,modalidades,Solo texto,2.0498,0.0365,0.0538,-0.0354,0.0299,0.0152,1.0000,23760,0.49,0.0152,1352072,0.1769,3942.5884
6,vla_referencia,referencia,VLA estándar,1.2671,0.0363,0.0534,0.1190,0.1980,0.1322,0.3944,1074,0.81,0.9516,1352072,0.3420,14019.8794

Resumen guardado en C:\TFM_Codigo\TFM-VLA\results\experimentos_vla\resumen_experimentos.csv
El conjunto de test no se ha usado. El notebook 09 evaluará el modelo seleccionado.

## Resumen

El notebook ha comparado la profundidad y dimensión del Transformer, así como la aportación de imagen y texto. Los resultados quedan disponibles para seleccionar la configuración final antes de evaluarla sobre test en el notebook 09 y generar las gráficas definitivas en el notebook 10.