# 08 — Experimentos

Este notebook compara variantes ligeras del modelo VLA. Todos los experimentos usan exactamente las mismas particiones de **train** y **validation**; el conjunto de **test** queda reservado para el notebook 09.

## 1. Configuración e imports

Se reutilizan los embeddings cacheados de CLIP del notebook 04. CLIP no se vuelve a entrenar: solo se entrenan el Transformer de fusión y el decodificador.

In [ ]:
from pathlib import Path
import json
import random
import sys

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader, TensorDataset

NOTEBOOK_DIR = Path.cwd().resolve()
ROOT_DIR = NOTEBOOK_DIR.parent if (NOTEBOOK_DIR.parent / 'src').exists() else NOTEBOOK_DIR
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

from src.evaluation import benchmark_inference, evaluate_actions, select_f1_threshold
from src.project_config import CACHE_DIR, PROJECT_DIR, experiment_dirs
from src.train import load_checkpoint, train_model
from src.vla_model import VLA

ROOT_DIR = PROJECT_DIR
SEED = 42
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
BATCH_SIZE = 16
LEARNING_RATE = 3e-4
WEIGHT_DECAY = 1e-4
EPOCHS_MAX = 3 #25
PATIENCE = 7
# None usa todas las muestras. Puede cambiarse por un entero para una prueba rápida.
MAX_TRAIN_SAMPLES = 5 # None

def fijar_semilla(seed=SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

fijar_semilla()
RUTAS = experiment_dirs('experimentos_vla')
print(f'Dispositivo: {DEVICE} | semilla: {SEED}')
print(f'Resultados: {RUTAS["results"]}')

Dispositivo: cpu | semilla: 42
Resultados: C:\TFM_Codigo\TFM-VLA\results\experimentos_vla

## 2. Carga de datos y preparación de lotes

Se cargan únicamente `train` y `validation`. Las acciones tienen el orden `[terminate, x, y, z, rx, ry, rz, gripper]`.

In [2]:
EMBEDDING_DIM = 512
OUTPUT_DIM = 8

def cargar_particion(nombre):
    ruta = CACHE_DIR / f'{nombre}.npz'
    if not ruta.exists():
        raise FileNotFoundError(f'No existe {ruta}. Ejecuta antes 04_clip_embeddings.ipynb.')
    with np.load(ruta) as datos:
        requeridas = {'imagenes_static', 'imagenes_gripper', 'textos', 'acciones'}
        if not requeridas.issubset(datos.files):
            raise KeyError(f'{nombre}: se esperaban las claves {requeridas}')
        arrays = tuple(np.asarray(datos[clave], dtype=np.float32) for clave in
                       ('imagenes_static', 'imagenes_gripper', 'textos', 'acciones'))
    static, gripper, texto, acciones = arrays
    if not (len(static) == len(gripper) == len(texto) == len(acciones)):
        raise ValueError(f'{nombre}: longitudes inconsistentes')
    if static.shape[1:] != (EMBEDDING_DIM,) or gripper.shape[1:] != (EMBEDDING_DIM,) or texto.shape[1:] != (EMBEDDING_DIM,):
        raise ValueError(f'{nombre}: embeddings con dimensión inesperada')
    if acciones.shape[1:] != (OUTPUT_DIM,) or not all(np.isfinite(x).all() for x in arrays):
        raise ValueError(f'{nombre}: acciones o embeddings no válidos')
    return arrays

particiones = {nombre: cargar_particion(nombre) for nombre in ('train', 'validation')}
if MAX_TRAIN_SAMPLES is not None:
    particiones['train'] = tuple(array[:MAX_TRAIN_SAMPLES] for array in particiones['train'])

for nombre, (static, gripper, texto, acciones) in particiones.items():
    print(f'{nombre:10s}: static={static.shape}, gripper={gripper.shape}, texto={texto.shape}, acciones={acciones.shape}')

with (ROOT_DIR / 'data' / 'parametros_normalizacion.json').open(encoding='utf-8') as archivo:
    normalizacion = json.load(archivo)
MINIMO = np.asarray(normalizacion['minimo'], dtype=np.float32)
ESCALA = np.asarray(normalizacion['escala'], dtype=np.float32)

train     : static=(190212, 512), gripper=(190212, 512), texto=(190212, 512), acciones=(190212, 8)
validation: static=(23760, 512), gripper=(23760, 512), texto=(23760, 512), acciones=(23760, 8)

## 3. Funciones reutilizables

La misma función entrena, recupera el mejor checkpoint y calcula las métricas de validación de cada variante. Esto evita repetir código y garantiza que el procedimiento sea igual en todos los casos.

In [3]:
def aplicar_modalidades(arrays, modalidad):
    """Anula modalidades para conservar la misma arquitectura de tres tokens."""
    static, gripper, texto, acciones = arrays
    if modalidad == 'imagen':
        texto = np.zeros_like(texto)
    elif modalidad == 'texto':
        static = np.zeros_like(static)
        gripper = np.zeros_like(gripper)
    elif modalidad != 'imagen_texto':
        raise ValueError(f'Modalidad no reconocida: {modalidad}')
    return static, gripper, texto, acciones

def crear_loaders(train_arrays, validation_arrays):
    train_dataset = TensorDataset(*(torch.from_numpy(array) for array in train_arrays))
    validation_dataset = TensorDataset(*(torch.from_numpy(array) for array in validation_arrays))
    # Se reinicia el generador para que el orden de train sea comparable.
    generator = torch.Generator().manual_seed(SEED)
    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, generator=generator, num_workers=0)
    validation_loader = DataLoader(validation_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
    return train_loader, validation_loader

def crear_modelo(config):
    return VLA(
        clip_encoder=None, embedding_dim=EMBEDDING_DIM, fusion_dim=config['fusion_dim'],
        decoder_hidden_dim=128, num_layers=config['num_layers'], num_heads=4,
        feedforward_dim=config['fusion_dim'] * 2, dropout=0.1,
    ).to(DEVICE)

def predecir(modelo, loader):
    predicciones, objetivos = [], []
    modelo.eval()
    with torch.no_grad():
        for static, gripper, texto, accion in loader:
            salida = modelo(static_embeddings=static.to(DEVICE), gripper_embeddings=gripper.to(DEVICE), text_embeddings=texto.to(DEVICE))
            predicciones.append(salida.cpu())
            objetivos.append(accion)
    return torch.cat(predicciones).numpy(), torch.cat(objetivos).numpy()

def ejecutar_experimento(config):
    fijar_semilla()
    nombre = config['name']
    rutas = experiment_dirs(f'experimentos_vla/{nombre}')
    train_arrays = aplicar_modalidades(particiones['train'], config['modalidad'])
    validation_arrays = aplicar_modalidades(particiones['validation'], config['modalidad'])
    train_loader, validation_loader = crear_loaders(train_arrays, validation_arrays)
    positivos_terminate = int((train_arrays[3][:, 0] >= 0.5).sum())
    negativos_terminate = len(train_arrays[3]) - positivos_terminate
    terminate_positive_weight = negativos_terminate / max(positivos_terminate, 1)
    modelo = crear_modelo(config)
    optimizador = torch.optim.AdamW(modelo.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    checkpoint_path = rutas['checkpoints'] / 'best.pt'
    configuracion = {**config, 'seed': SEED, 'batch_size': BATCH_SIZE, 'learning_rate': LEARNING_RATE,
                     'weight_decay': WEIGHT_DECAY, 'epochs_max': EPOCHS_MAX, 'patience': PATIENCE,
                     'terminate_positive_weight': terminate_positive_weight}
    resumen = train_model(modelo, train_loader, validation_loader, optimizador, DEVICE,
                           epochs=EPOCHS_MAX, patience=PATIENCE, checkpoint_path=checkpoint_path, config=configuracion,
                           terminate_positive_weight=terminate_positive_weight)
    recuperado = crear_modelo(config)
    checkpoint = load_checkpoint(checkpoint_path, recuperado, map_location=DEVICE)
    y_pred, y_true = predecir(recuperado, validation_loader)
    terminate_threshold = select_f1_threshold(y_pred[:, 0], y_true[:, 0])
    metricas = evaluate_actions(y_pred, y_true, MINIMO, ESCALA, terminate_threshold=terminate_threshold)
    total = sum(p.numel() for p in recuperado.parameters())
    entrenables = sum(p.numel() for p in recuperado.parameters() if p.requires_grad)
    n_tiempo = min(32, len(validation_arrays[0]))
    entrada_tiempo = [torch.from_numpy(array[:n_tiempo]).to(DEVICE) for array in validation_arrays[:3]]
    inferencia = benchmark_inference(lambda: recuperado(static_embeddings=entrada_tiempo[0], gripper_embeddings=entrada_tiempo[1], text_embeddings=entrada_tiempo[2]), n_tiempo)
    resultado = {**configuracion, 'best_epoch': resumen['best_epoch'],
                 'best_validation_loss': resumen['best_validation_loss'],
                 'epochs_executed': resumen['epochs_executed'],
                 'total_training_time_seconds': resumen['total_training_time_seconds'],
                 'parameters_total': total, 'parameters_trainable': entrenables, 'terminate_threshold': terminate_threshold,
                 'validation_metrics': metricas, 'cached_inference': inferencia,
                 'checkpoint': str(checkpoint_path), 'history': resumen['history'], 'test_used': False}
    with (rutas['results'] / 'resultado.json').open('w', encoding='utf-8') as archivo:
        json.dump(resultado, archivo, indent=2, ensure_ascii=False)
    print(f'{nombre}: validation loss={resultado["best_validation_loss"]:.6f} | terminate F1={metricas["terminate"]["f1"]:.4f} | época={resultado["best_epoch"]}')
    return resultado

## 4. Configuraciones a comparar

Se entrena una referencia VLA estándar y cinco variantes. La referencia (2 capas y dimensión 256) se reutiliza en la comparación de capas, dimensión y modalidades, por lo que no se entrena dos veces.

In [4]:
EXPERIMENTOS = [
    {'name': 'vla_referencia', 'grupo': 'referencia', 'descripcion': 'VLA estándar', 'num_layers': 2, 'fusion_dim': 256, 'modalidad': 'imagen_texto'},
    {'name': 'capas_1', 'grupo': 'capas', 'descripcion': '1 capa', 'num_layers': 1, 'fusion_dim': 256, 'modalidad': 'imagen_texto'},
    {'name': 'capas_3', 'grupo': 'capas', 'descripcion': '3 capas', 'num_layers': 3, 'fusion_dim': 256, 'modalidad': 'imagen_texto'},
    {'name': 'dimension_128', 'grupo': 'dimension', 'descripcion': 'd_model = 128', 'num_layers': 2, 'fusion_dim': 128, 'modalidad': 'imagen_texto'},
    {'name': 'solo_imagen', 'grupo': 'modalidades', 'descripcion': 'Solo imagen', 'num_layers': 2, 'fusion_dim': 256, 'modalidad': 'imagen'},
    {'name': 'solo_texto', 'grupo': 'modalidades', 'descripcion': 'Solo texto', 'num_layers': 2, 'fusion_dim': 256, 'modalidad': 'texto'},
]
pd.DataFrame(EXPERIMENTOS)[['name', 'grupo', 'descripcion', 'num_layers', 'fusion_dim', 'modalidad']]

,name,grupo,descripcion,num_layers,fusion_dim,modalidad
0,vla_referencia,referencia,VLA estándar,2,256,imagen_texto
1,capas_1,capas,1 capa,1,256,imagen_texto
2,capas_3,capas,3 capas,3,256,imagen_texto
3,dimension_128,dimension,d_model = 128,2,128,imagen_texto
4,solo_imagen,modalidades,Solo imagen,2,256,imagen
5,solo_texto,modalidades,Solo texto,2,256,texto

## 5. Ejecución de los experimentos

Cada configuración empieza con pesos iniciales y orden de entrenamiento reproducibles. En CPU, el conjunto completo puede requerir bastante tiempo; `MAX_TRAIN_SAMPLES` permite una ejecución de comprobación más corta sin modificar el flujo.

In [5]:
resultados = [ejecutar_experimento(config) for config in EXPERIMENTOS]

Entrenamiento 1/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/25 | train_loss=0.440487 | validation_loss=0.411034 | 362.0s

Entrenamiento 2/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/25 | train_loss=0.351353 | validation_loss=0.345196 | 406.6s

Entrenamiento 3/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/25 | train_loss=0.313994 | validation_loss=0.304612 | 390.7s

Entrenamiento 4/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/25 | train_loss=0.291172 | validation_loss=0.336260 | 376.5s

Entrenamiento 5/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/25 | train_loss=0.275156 | validation_loss=0.310765 | 373.2s

Entrenamiento 6/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/25 | train_loss=0.264277 | validation_loss=0.295398 | 372.6s

Entrenamiento 7/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/25 | train_loss=0.256340 | validation_loss=0.288105 | 368.5s

Entrenamiento 8/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/25 | train_loss=0.249773 | validation_loss=0.285725 | 371.6s

Entrenamiento 9/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/25 | train_loss=0.245218 | validation_loss=0.288552 | 366.5s

Entrenamiento 10/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/25 | train_loss=0.238011 | validation_loss=0.289478 | 370.5s

Entrenamiento 11/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 11/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 11/25 | train_loss=0.231394 | validation_loss=0.275293 | 371.5s

Entrenamiento 12/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 12/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 12/25 | train_loss=0.227167 | validation_loss=0.303574 | 363.2s

Entrenamiento 13/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 13/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 13/25 | train_loss=0.221263 | validation_loss=0.267484 | 368.3s

Entrenamiento 14/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 14/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 14/25 | train_loss=0.218154 | validation_loss=0.280766 | 366.6s

Entrenamiento 15/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 15/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 15/25 | train_loss=0.215516 | validation_loss=0.278533 | 366.8s

Entrenamiento 16/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 16/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 16/25 | train_loss=0.210091 | validation_loss=0.283768 | 365.3s

Entrenamiento 17/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 17/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 17/25 | train_loss=0.204776 | validation_loss=0.271995 | 362.1s

Entrenamiento 18/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 18/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 18/25 | train_loss=0.201090 | validation_loss=0.266220 | 373.9s

Entrenamiento 19/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 19/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 19/25 | train_loss=0.197978 | validation_loss=0.277221 | 427.0s

Entrenamiento 20/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 20/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 20/25 | train_loss=0.194324 | validation_loss=0.267982 | 363.9s

Entrenamiento 21/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 21/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 21/25 | train_loss=0.189963 | validation_loss=0.294955 | 404.1s

Entrenamiento 22/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 22/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 22/25 | train_loss=0.188080 | validation_loss=0.262132 | 388.1s

Entrenamiento 23/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 23/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 23/25 | train_loss=0.190506 | validation_loss=0.280191 | 364.9s

Entrenamiento 24/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 24/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 24/25 | train_loss=0.186147 | validation_loss=0.279446 | 367.4s

Entrenamiento 25/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 25/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 25/25 | train_loss=0.188099 | validation_loss=0.264047 | 364.1s
vla_referencia: validation loss=0.262132 | época=22

Entrenamiento 1/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/25 | train_loss=0.434749 | validation_loss=0.407387 | 225.9s

Entrenamiento 2/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/25 | train_loss=0.344926 | validation_loss=0.361159 | 224.6s

Entrenamiento 3/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/25 | train_loss=0.304732 | validation_loss=0.310240 | 223.0s

Entrenamiento 4/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/25 | train_loss=0.279947 | validation_loss=0.307283 | 223.2s

Entrenamiento 5/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/25 | train_loss=0.262432 | validation_loss=0.299695 | 222.0s

Entrenamiento 6/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/25 | train_loss=0.250267 | validation_loss=0.298611 | 224.0s

Entrenamiento 7/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/25 | train_loss=0.239733 | validation_loss=0.286858 | 219.9s

Entrenamiento 8/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/25 | train_loss=0.230245 | validation_loss=0.272410 | 220.4s

Entrenamiento 9/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/25 | train_loss=0.220973 | validation_loss=0.270940 | 228.3s

Entrenamiento 10/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/25 | train_loss=0.214465 | validation_loss=0.274325 | 222.7s

Entrenamiento 11/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 11/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 11/25 | train_loss=0.207522 | validation_loss=0.274434 | 222.3s

Entrenamiento 12/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 12/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 12/25 | train_loss=0.201946 | validation_loss=0.291191 | 222.2s

Entrenamiento 13/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 13/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 13/25 | train_loss=0.196903 | validation_loss=0.266725 | 221.1s

Entrenamiento 14/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 14/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 14/25 | train_loss=0.191963 | validation_loss=0.281040 | 223.3s

Entrenamiento 15/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 15/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 15/25 | train_loss=0.187279 | validation_loss=0.269595 | 221.8s

Entrenamiento 16/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 16/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 16/25 | train_loss=0.183460 | validation_loss=0.296449 | 221.4s

Entrenamiento 17/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 17/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 17/25 | train_loss=0.180094 | validation_loss=0.275575 | 225.2s

Entrenamiento 18/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 18/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 18/25 | train_loss=0.175985 | validation_loss=0.275218 | 221.0s

Entrenamiento 19/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 19/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 19/25 | train_loss=0.171988 | validation_loss=0.269927 | 220.8s

Entrenamiento 20/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 20/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 20/25 | train_loss=0.168732 | validation_loss=0.251571 | 224.7s

Entrenamiento 21/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 21/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 21/25 | train_loss=0.166223 | validation_loss=0.275482 | 222.9s

Entrenamiento 22/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 22/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 22/25 | train_loss=0.162296 | validation_loss=0.267325 | 225.2s

Entrenamiento 23/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 23/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 23/25 | train_loss=0.160141 | validation_loss=0.295711 | 221.3s

Entrenamiento 24/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 24/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 24/25 | train_loss=0.159001 | validation_loss=0.256743 | 222.0s

Entrenamiento 25/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 25/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 25/25 | train_loss=0.155193 | validation_loss=0.262741 | 228.3s
capas_1: validation loss=0.251571 | época=20

Entrenamiento 1/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/25 | train_loss=0.449470 | validation_loss=0.412027 | 495.7s

Entrenamiento 2/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/25 | train_loss=0.364542 | validation_loss=0.373847 | 529.2s

Entrenamiento 3/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/25 | train_loss=0.348792 | validation_loss=0.335192 | 522.8s

Entrenamiento 4/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/25 | train_loss=0.333920 | validation_loss=0.331028 | 515.1s

Entrenamiento 5/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/25 | train_loss=0.305509 | validation_loss=0.324146 | 509.2s

Entrenamiento 6/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/25 | train_loss=0.304760 | validation_loss=0.329969 | 507.8s

Entrenamiento 7/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/25 | train_loss=0.281458 | validation_loss=0.316745 | 514.3s

Entrenamiento 8/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/25 | train_loss=0.271385 | validation_loss=0.321131 | 510.5s

Entrenamiento 9/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/25 | train_loss=0.259227 | validation_loss=0.294114 | 502.6s

Entrenamiento 10/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/25 | train_loss=0.253539 | validation_loss=0.292782 | 507.4s

Entrenamiento 11/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 11/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 11/25 | train_loss=0.249370 | validation_loss=0.295427 | 503.6s

Entrenamiento 12/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 12/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 12/25 | train_loss=0.241685 | validation_loss=0.290689 | 503.3s

Entrenamiento 13/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 13/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 13/25 | train_loss=0.240593 | validation_loss=0.267257 | 507.3s

Entrenamiento 14/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 14/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 14/25 | train_loss=0.251729 | validation_loss=0.266719 | 515.2s

Entrenamiento 15/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 15/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 15/25 | train_loss=0.236716 | validation_loss=0.298010 | 508.0s

Entrenamiento 16/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 16/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 16/25 | train_loss=0.236533 | validation_loss=0.285682 | 504.5s

Entrenamiento 17/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 17/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 17/25 | train_loss=0.237257 | validation_loss=0.282605 | 600.7s

Entrenamiento 18/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 18/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 18/25 | train_loss=0.226477 | validation_loss=0.264832 | 530.5s

Entrenamiento 19/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 19/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 19/25 | train_loss=0.217855 | validation_loss=0.278055 | 511.5s

Entrenamiento 20/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 20/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 20/25 | train_loss=0.212669 | validation_loss=0.262562 | 509.7s

Entrenamiento 21/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 21/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 21/25 | train_loss=0.222134 | validation_loss=0.286178 | 514.3s

Entrenamiento 22/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 22/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 22/25 | train_loss=0.207653 | validation_loss=0.272825 | 515.2s

Entrenamiento 23/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 23/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 23/25 | train_loss=0.206329 | validation_loss=0.283216 | 509.9s

Entrenamiento 24/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 24/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 24/25 | train_loss=0.203254 | validation_loss=0.299726 | 511.5s

Entrenamiento 25/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 25/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 25/25 | train_loss=0.202133 | validation_loss=0.277069 | 517.4s
capas_3: validation loss=0.262562 | época=20

Entrenamiento 1/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/25 | train_loss=0.432859 | validation_loss=0.403910 | 225.6s

Entrenamiento 2/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/25 | train_loss=0.343478 | validation_loss=0.385062 | 218.8s

Entrenamiento 3/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/25 | train_loss=0.307685 | validation_loss=0.311463 | 220.8s

Entrenamiento 4/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/25 | train_loss=0.284246 | validation_loss=0.336136 | 223.8s

Entrenamiento 5/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/25 | train_loss=0.266413 | validation_loss=0.323023 | 220.0s

Entrenamiento 6/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/25 | train_loss=0.254719 | validation_loss=0.287706 | 219.4s

Entrenamiento 7/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/25 | train_loss=0.242347 | validation_loss=0.299353 | 224.9s

Entrenamiento 8/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/25 | train_loss=0.235379 | validation_loss=0.270280 | 221.1s

Entrenamiento 9/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/25 | train_loss=0.228390 | validation_loss=0.277831 | 222.9s

Entrenamiento 10/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/25 | train_loss=0.221301 | validation_loss=0.265205 | 221.7s

Entrenamiento 11/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 11/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 11/25 | train_loss=0.215505 | validation_loss=0.258559 | 221.2s

Entrenamiento 12/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 12/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 12/25 | train_loss=0.210273 | validation_loss=0.282270 | 223.5s

Entrenamiento 13/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 13/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 13/25 | train_loss=0.204619 | validation_loss=0.274741 | 220.6s

Entrenamiento 14/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 14/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 14/25 | train_loss=0.201221 | validation_loss=0.273208 | 222.1s

Entrenamiento 15/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 15/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 15/25 | train_loss=0.196745 | validation_loss=0.256541 | 225.4s

Entrenamiento 16/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 16/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 16/25 | train_loss=0.194161 | validation_loss=0.267405 | 221.4s

Entrenamiento 17/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 17/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 17/25 | train_loss=0.190285 | validation_loss=0.243872 | 226.2s

Entrenamiento 18/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 18/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 18/25 | train_loss=0.187926 | validation_loss=0.259970 | 223.8s

Entrenamiento 19/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 19/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 19/25 | train_loss=0.184404 | validation_loss=0.255706 | 226.4s

Entrenamiento 20/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 20/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 20/25 | train_loss=0.182099 | validation_loss=0.243042 | 228.5s

Entrenamiento 21/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 21/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 21/25 | train_loss=0.180612 | validation_loss=0.264555 | 225.1s

Entrenamiento 22/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 22/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 22/25 | train_loss=0.177597 | validation_loss=0.256642 | 273.6s

Entrenamiento 23/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 23/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 23/25 | train_loss=0.174889 | validation_loss=0.252770 | 231.2s

Entrenamiento 24/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 24/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 24/25 | train_loss=0.173029 | validation_loss=0.265822 | 227.4s

Entrenamiento 25/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 25/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 25/25 | train_loss=0.170802 | validation_loss=0.265690 | 232.2s
dimension_128: validation loss=0.243042 | época=20

Entrenamiento 1/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/25 | train_loss=0.455906 | validation_loss=0.436520 | 374.5s

Entrenamiento 2/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/25 | train_loss=0.379810 | validation_loss=0.387719 | 394.9s

Entrenamiento 3/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/25 | train_loss=0.347574 | validation_loss=0.346882 | 381.6s

Entrenamiento 4/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/25 | train_loss=0.328311 | validation_loss=0.350384 | 374.9s

Entrenamiento 5/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/25 | train_loss=0.310428 | validation_loss=0.339655 | 373.6s

Entrenamiento 6/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/25 | train_loss=0.294831 | validation_loss=0.334451 | 368.8s

Entrenamiento 7/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/25 | train_loss=0.282697 | validation_loss=0.352480 | 370.8s

Entrenamiento 8/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/25 | train_loss=0.269316 | validation_loss=0.331238 | 374.8s

Entrenamiento 9/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/25 | train_loss=0.260919 | validation_loss=0.303518 | 367.5s

Entrenamiento 10/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/25 | train_loss=0.251608 | validation_loss=0.326281 | 421.1s

Entrenamiento 11/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 11/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 11/25 | train_loss=0.242761 | validation_loss=0.320287 | 370.0s

Entrenamiento 12/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 12/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 12/25 | train_loss=0.237649 | validation_loss=0.385488 | 367.9s

Entrenamiento 13/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 13/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 13/25 | train_loss=0.228373 | validation_loss=0.287884 | 368.9s

Entrenamiento 14/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 14/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 14/25 | train_loss=0.222276 | validation_loss=0.317910 | 367.9s

Entrenamiento 15/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 15/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 15/25 | train_loss=0.215773 | validation_loss=0.298070 | 367.2s

Entrenamiento 16/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 16/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 16/25 | train_loss=0.213993 | validation_loss=0.277837 | 366.7s

Entrenamiento 17/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 17/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 17/25 | train_loss=0.206665 | validation_loss=0.283898 | 369.1s

Entrenamiento 18/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 18/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 18/25 | train_loss=0.202093 | validation_loss=0.292141 | 372.2s

Entrenamiento 19/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 19/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 19/25 | train_loss=0.200566 | validation_loss=0.270668 | 371.6s

Entrenamiento 20/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 20/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 20/25 | train_loss=0.194704 | validation_loss=0.276620 | 371.7s

Entrenamiento 21/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 21/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 21/25 | train_loss=0.189959 | validation_loss=0.275630 | 368.0s

Entrenamiento 22/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 22/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 22/25 | train_loss=0.186581 | validation_loss=0.277186 | 368.7s

Entrenamiento 23/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 23/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 23/25 | train_loss=0.184275 | validation_loss=0.279703 | 372.2s

Entrenamiento 24/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 24/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 24/25 | train_loss=0.179879 | validation_loss=0.296062 | 372.9s

Entrenamiento 25/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 25/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 25/25 | train_loss=0.177377 | validation_loss=0.269106 | 369.5s
solo_imagen: validation loss=0.269106 | época=25

Entrenamiento 1/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 1/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 01/25 | train_loss=0.761472 | validation_loss=0.764622 | 389.1s

Entrenamiento 2/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 2/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 02/25 | train_loss=0.764430 | validation_loss=0.762878 | 375.3s

Entrenamiento 3/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 3/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 03/25 | train_loss=0.760677 | validation_loss=0.757334 | 379.0s

Entrenamiento 4/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 4/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 04/25 | train_loss=0.760267 | validation_loss=0.763835 | 378.5s

Entrenamiento 5/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 5/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 05/25 | train_loss=0.764441 | validation_loss=0.763352 | 376.5s

Entrenamiento 6/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 6/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 06/25 | train_loss=0.764226 | validation_loss=0.763547 | 382.5s

Entrenamiento 7/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 7/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 07/25 | train_loss=0.764154 | validation_loss=0.761616 | 380.0s

Entrenamiento 8/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 8/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 08/25 | train_loss=0.761585 | validation_loss=0.754999 | 385.8s

Entrenamiento 9/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 9/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 09/25 | train_loss=0.761302 | validation_loss=0.754158 | 392.7s

Entrenamiento 10/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 10/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 10/25 | train_loss=0.759098 | validation_loss=0.758771 | 390.6s

Entrenamiento 11/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 11/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 11/25 | train_loss=0.758116 | validation_loss=0.757090 | 383.8s

Entrenamiento 12/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 12/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 12/25 | train_loss=0.759382 | validation_loss=0.753581 | 385.6s

Entrenamiento 13/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 13/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 13/25 | train_loss=0.757765 | validation_loss=0.755615 | 382.0s

Entrenamiento 14/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 14/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 14/25 | train_loss=0.758297 | validation_loss=0.759911 | 380.7s

Entrenamiento 15/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 15/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 15/25 | train_loss=0.759626 | validation_loss=0.758219 | 380.3s

Entrenamiento 16/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 16/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 16/25 | train_loss=0.759526 | validation_loss=0.756302 | 381.1s

Entrenamiento 17/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 17/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 17/25 | train_loss=0.756259 | validation_loss=0.754436 | 386.7s

Entrenamiento 18/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 18/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 18/25 | train_loss=0.756124 | validation_loss=0.756087 | 388.2s

Entrenamiento 19/25:   0%|          | 0/11889 [00:00<?, ?lote/s]

Validación 19/25:   0%|          | 0/1485 [00:00<?, ?lote/s]

Época 19/25 | train_loss=0.755813 | validation_loss=0.755205 | 383.5s
Early stopping: 7 épocas sin mejora.
solo_texto: validation loss=0.753581 | época=12

## 6. Comparación con el baseline MLP

El baseline se entrena en el notebook 05. Si su archivo de resultados de validación está disponible, se añade como referencia; si no, el notebook sigue siendo ejecutable y muestra una advertencia.

In [6]:
def cargar_baseline():
    ruta = ROOT_DIR / 'results' / 'baseline_mlp_binary_phase1' / 'baseline_mlp_binary_validation.json'
    if not ruta.exists():
        print('Baseline no disponible: ejecuta 05_baseline_mlp.ipynb para añadirlo a la comparación.')
        return None
    with ruta.open(encoding='utf-8') as archivo:
        baseline = json.load(archivo)
    return {
        'name': 'baseline_mlp', 'grupo': 'baseline', 'descripcion': 'MLP del notebook 05',
        'best_validation_loss': baseline['best_validation_loss'],
        'parameters_trainable': baseline['computational_efficiency']['trainable_parameters'],
        'validation_metrics': baseline['validation_action_metrics'],
    }

baseline = cargar_baseline()
if baseline is not None:
    resultados.append(baseline)

Baseline no disponible: ejecuta 05_baseline_mlp.ipynb para añadirlo a la comparación.

## 7. Resumen y guardado

La tabla resume las métricas principales de validación. El tiempo de inferencia corresponde solo al VLA sobre embeddings cacheados, porque CLIP está congelado e idéntico en todas las variantes; la medición completa del sistema se realizará en el notebook 09.

In [7]:
def fila_resumen(resultado):
    metricas = resultado['validation_metrics']
    fila = {
        'experimento': resultado['name'], 'grupo': resultado['grupo'], 'descripcion': resultado['descripcion'],
        'validation_loss': resultado['best_validation_loss'],
        'mae': metricas['continuous_normalized']['mae'],
        'rmse': metricas['continuous_normalized']['rmse'],
        'coseno_xyz': metricas['xyz_denormalized_cosine_similarity'],
        'terminate_f1': metricas['terminate']['f1'],
        'terminate_precision': metricas['terminate']['precision'],
        'terminate_recall': metricas['terminate']['recall'],
        'terminate_predicted_positives': metricas['terminate']['predicted_positives'],
        'terminate_threshold': metricas['terminate']['threshold'],
        'terminate_accuracy': metricas['terminate']['accuracy'],
        'parametros_entrenables': resultado['parameters_trainable'],
    }
    if 'cached_inference' in resultado:
        fila['inferencia_ms_muestra'] = resultado['cached_inference']['mean_ms_per_sample']
        fila['tiempo_entrenamiento_s'] = resultado['total_training_time_seconds']
    return fila

tabla_resultados = pd.DataFrame([fila_resumen(resultado) for resultado in resultados])
tabla_resultados = tabla_resultados.sort_values(['grupo', 'experimento']).reset_index(drop=True)
tabla_path = RUTAS['results'] / 'resumen_experimentos.csv'
json_path = RUTAS['results'] / 'resumen_experimentos.json'
tabla_resultados.to_csv(tabla_path, index=False)
with json_path.open('w', encoding='utf-8') as archivo:
    json.dump(resultados, archivo, indent=2, ensure_ascii=False)

display(tabla_resultados.round(4))
print(f'Resumen guardado en {tabla_path}')
print('El conjunto de test no se ha usado. El notebook 09 evaluará el modelo seleccionado.')

,experimento,grupo,descripcion,validation_loss,mae,rmse,coseno_xyz,terminate_f1,terminate_accuracy,parametros_entrenables,inferencia_ms_muestra,tiempo_entrenamiento_s
0,capas_1,capas,1 capa,0.2516,0.0348,0.0491,0.4335,0.0,0.9848,824968,0.1022,5578.0737
1,capas_3,capas,3 capas,0.2626,0.0367,0.0537,0.0723,0.0,0.9848,1879176,0.1914,12878.8664
2,dimension_128,dimension,d_model = 128,0.2430,0.0348,0.0503,0.3782,0.0,0.9848,414472,0.0822,5648.1520
3,solo_imagen,modalidades,Solo imagen,0.2691,0.0358,0.0526,0.1967,0.0,0.9848,1352072,0.1812,9347.8002
4,solo_texto,modalidades,Solo texto,0.7536,0.0364,0.0538,0.0354,0.0,0.9848,1352072,0.1420,7282.1339
5,vla_referencia,referencia,VLA estándar,0.2621,0.0364,0.0522,0.1881,0.0,0.9848,1352072,0.1883,9376.6472

Resumen guardado en C:\TFM_Codigo\TFM-VLA\results\experimentos_vla\resumen_experimentos.csv
El conjunto de test no se ha usado. El notebook 09 evaluará el modelo seleccionado.

## Resumen

El notebook ha comparado la profundidad y dimensión del Transformer, así como la aportación de imagen y texto. Los resultados quedan disponibles para seleccionar la configuración final antes de evaluarla sobre test en el notebook 09 y generar las gráficas definitivas en el notebook 10.